### ISSUE TITLE
How to run other datesets like Market in OpenLoris?

### ISSUE THREAD

**Issue by drscopus** [hellovuong/ORB_SLAM_odom#1]
Hi, @hellovuong , I have run mono_odom succesfully on office dataset in OpenLoris.  I have to say, it works pretty well. These packages are good job! Thank you for your contribution.

I also want to test other datasets mentioned in your repositories (https://github.com/hellovuong/ORB_SLAM3) and your papers. I have checked all branches in your repositories but can't find the correct odom files. 

Would you like to provide the odom txt files corresponding to corridor and market datasets? Many thanks!

**Comment by hellovuong** [comment]
Hi @drscopus, I am sorry for late reply. Unfortunately, I didn't save OpenLoris datasets on my computer anymore so basically I lost all of the odom files that I used before. However you can find the script to generate once for yourself [here](https://gist.github.com/hellovuong/a91b7717b8cbb781a4db10fd875f6775).

**Comment by hellovuong** [comment]
I also would like to comment about the result. Basically the result dominants by the odometry quality. If odometry is good, the SLAM result is good and other ways also (that what you will observe in corridor sequence, market sequece of OpenLoris datasets), only loop closure can improve the estimation quality if odometry is bad. So you may want to checkout this [works](https://arxiv.org/abs/1910.09875) to have idea about better way to fusing Odometry.

**Comment by drscopus** [comment]
@hellovuong  Many thanks to your instructions! Now it succeeds on a Market dataset of OpenLoris. We'll try to run it on our own dataset.
