### ISSUE TITLE
What is the difference between this work and Fan zheng's?

### ISSUE THREAD

**Issue by drscopus** [hellovuong/ORB_SLAM_odom#2]
hi, @hellovuong , I want to study deeply [your code](https://github.com/hellovuong/ORB_SLAM3) but has no reference papers. So I can not get the idea of your modificaition on the ORB_SLAM3 code.  Although you quote the papers of Fan Zheng, I don't know which repositories [se2lam](https://github.com/izhengfan/se2lam) or [se2clam](https://github.com/izhengfan/se2clam)  and which branches/commits after which your work continue on. 

For now the documents we only can rely on are the result figures in the doc directory of [your code]((https://github.com/hellovuong/ORB_SLAM3)). These figures don't show the details of your modification. 

Would you like to give more instuctions on your work? 
Such as the dependant theories the you modification based on and the difference between your work and Fanzheng's code.

Thanks!

**Comment by hellovuong** [comment]
@drscopus Hi,  I just used the proposal factor from the se2lam paper and implemented it in ORB_SLAM.

**Comment by drscopus** [comment]
@hellovuong Many thanks to your reply! I am sorry that I am a newer to ORB_SLAM3 and se2lam. Would you like to give more hints about what "proposal factor" is ? Is "proposal factor"  the theory and computation way that how the odom-image residual items are defined and used?

**Comment by hellovuong** [comment]
This one is from se2lam: https://github.com/hellovuong/ORB_SLAM_odom/blob/main/src/EdgeSE2XYZ.cpp

**Comment by drscopus** [comment]
Thank you for your instruction! This issue will be closed.

**Comment by hellovuong** [comment]
Good luck with your project!
