### ISSUE TITLE
Is this project enough for pinhole camera data with odom?

### ISSUE THREAD

**Issue by drscopus** [hellovuong/ORB_SLAM_odom#3]
hi @hellovuong , thank you very much for your contribution by adding EdgeSE2XYZ to ORB_SLAM2. 
Is there improvement from this repository to  [ORB_SLAM3_ODOM](https://github.com/hellovuong/ORB_SLAM3) ?
If we use pinhole camera, is your ORB_SLAM_odom modified from ORB_SLAM2 enough? Thank you！

**Comment by hellovuong** [comment]
@drscopus It should be enough if you just use pinhole and odometry. ORB_SLAM3 has "RECENTLY_LOST" state, so it is a bit more stable than this version as I remember.

**Comment by drscopus** [comment]
Thank you for your reply!
